DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    username TEXT PRIMARY KEY,
    date_joined DATETIME DEFAULT CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS PASSWORD;
CREATE TABLE PASSWORD(
    username TEXT PRIMARY KEY,
    password_hash VARCHAR,
    salt VARCHAR,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP);