DROP TABLE USER;
CREATE TABLE USER(
    user_id INTEGER PRIMARY KEY,
    username TEXT,
    date_joined DATETIME DEFAULT CURRENT_TIMESTAMP);

DROP TABLE PASSWORD;
CREATE TABLE PASSWORD(
    user_id INTEGER PRIMARY KEY,
    password_hash,
    salt,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP);